version: '3.9'

services:
  chroma:
    image: chromadb/chroma:latest
    container_name: lead_scrapper_chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
